<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CommonGrpcObject\CommonGrpcObject.csproj" />
      <ProjectReference Include="..\ObjectHandleFlow\ObjectHandleFlow.csproj" />
      <ProjectReference Include="..\ProjectEnums\ProjectEnums.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql" Version="8.0.3" />
      <PackageReference Include="protobuf-net.Core" Version="3.2.56" />
    </ItemGroup>

</Project>
