namespace Enums;

public enum EErrorCodeEnum
{
    NoErrorCode = 0,
    Success = 1,
    Fail = 2,
    ErrorCommentLimit = 3,
    ErrorCommentTime = 4,
    InternalExceptions = 500,
    Unauthorized = 401,
    NullRequestExceptions = 501,
    NotExistExceptions = 503,
    UserNullException = 504,
    IdNullException = 505,
    CurrentWebsiteNullException = 506,
    CurrentCompanyNullException = 507,
    PermissionDeny = 403,
    AntiXss = 502,
    InternalExceptionsNotDefine = 508,
    InternalExceptionsInService = 509,
    AccountPasswordIsConfigured = 510,
    OtpSendLimit = 511,
    OtpVerifyLimit = 512,
    OtpInvalid = 513,
    Grpc = 514,
    GrpcUnimplemented = 515,
    GrpcUnavailable = 516,
    GrpcInternal = 517,
    GrpcCancelled = 518,
    GrpcDeadlineExceeded = 519,
    GrpcNotFound = 520,
    GrpcAlreadyExists = 521,
    GrpcPermissionDenied = 522,
    GrpcResourceExhausted = 523,
    GrpcFailedPrecondition = 524,
    GrpcAborted = 525,
    GrpcOutOfRange = 526,
    GrpcUnauthenticated = 527,
    GrpcDataLoss = 528,
    GrpcUnknown = 529
}